sonar.projectKey=thaw-app_platform
sonar.organization=thaw-app

sonar.projectName=platform
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=test

sonar.javascript.lcov.reportPaths=coverage/lcov.info
