# yaml-language-server: $schema=./schema/members.schema.json
members:
  - username: diazdesandi
    teams:
      - slug: maintainers
        role: maintainer
      - slug: contributors
  - username: stonerl
    teams:
      - slug: maintainers
        role: maintainer
      - slug: contributors
  - username: nightah
    teams:
      - slug: contributors
      - slug: maintainers
  - username: 7a6163
    teams:
      - slug: contributors
  - username: alvst
    teams:
      - slug: contributors
  - username: camguillory
    teams:
      - slug: contributors
