# yaml-language-server: $schema=./schema/org.schema.json
owner: stonerl
organization: thaw-app

defaults:
  visibility: public
  defaultBranch: main
  deleteBranchOnMerge: true
  mergeStrategies:
    - squash
  squashMergeCommitTitle: PR_TITLE
  squashMergeCommitMessage: COMMIT_MESSAGES
  features:
    issues: true
    wiki: false
    projects: false
    discussions: false
